apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.fullname" . }}-post-install-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  bootstrap-admin.sh: |
{{ .Files.Get "files/bootstrap-admin.sh" | indent 4 }}