{{- if .Values.realm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.realm.configMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  {{ .Values.realm.configMapKey }}: |
    {{- .Values.realm.json | nindent 4 }}
{{- end }}