{{- if .Values.realm.file }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keycloak.realmConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  {{ .Values.realm.configMapKey }}: |
{{ .Files.Get .Values.realm.file | indent 4 }}
{{- end }}