{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  {{- if or .Values.gcp.workloadIdentity.enabled .Values.serviceAccount.annotations }}
  annotations:
    {{- if .Values.gcp.workloadIdentity.enabled }}
    iam.gke.io/gcp-service-account: {{ printf "%s@%s.iam.gserviceaccount.com" .Values.gcp.workloadIdentity.gcpServiceAccountName .Values.gcp.workloadIdentity.gcpProjectId | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}