apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-internal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.keycloak.httpPort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.keycloak.httpsPort }}
      targetPort: https
      protocol: TCP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}