apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "keycloak.fullname" . }}-internal
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  updateStrategy:
    type: {{ .Values.updateStrategy }}
  template:
    metadata:
      labels:
        {{- include "keycloak.selectorLabels" . | nindent 8 }}
      annotations:
        {{- if .Values.realm.file }}
        checksum/realm-config: {{ .Files.Get .Values.realm.file | sha256sum | quote }}
        {{- end }}
        checksum/db-credentials-secret: {{ .Values.keycloak.db.credentialsSecret | quote }}
        checksum/admin-credentials-secret: {{ .Values.keycloak.adminCredentialsSecret | quote }}
        checksum/tls-secret: {{ .Values.tls.secretName | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ .Values.podSecurityContext.fsGroup }}
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      restartPolicy: Always
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: keycloak-tls-server-cert-volume
          secret:
            secretName: {{ .Values.tls.secretName }}
            items:
              - key: tls.crt
                path: server-certificate.pem
              - key: tls.key
                path: server-certificate-key.pem
        {{- if .Values.realm.file }}
        - name: keycloak-realm-import-volume
          configMap:
            name: {{ include "keycloak.realmConfigMapName" . }}
            items:
              - key: {{ .Values.realm.configMapKey }}
                path: {{ .Values.realm.configMapKey }}
        {{- end }}
        {{- if .Values.cloudSqlProxy.enabled }}
        - name: gcp-service-account-credentials-volume
          secret:
            secretName: {{ .Values.cloudSqlProxy.credentialsSecret }}
            items:
              - key: gcp-service-account-credentials-json
                path: gcp-service-account-credentials.json
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      containers:
        {{- if .Values.cloudSqlProxy.enabled }}
        - name: cloud-sql-proxy
          image: "{{ .Values.cloudSqlProxy.image.repository }}:{{ .Values.cloudSqlProxy.image.tag }}"
          imagePullPolicy: {{ .Values.cloudSqlProxy.image.pullPolicy }}
          args:
            - "--private-ip"
            - {{ .Values.cloudSqlProxy.instanceConnectionName | quote }}
            - "--port={{ .Values.cloudSqlProxy.port }}"
            - "--address=0.0.0.0"
            - "--structured-logs"
            - "--credentials-file=/secrets/gcp/gcp-service-account-credentials.json"
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - name: gcp-service-account-credentials-volume
              mountPath: /secrets/gcp
              readOnly: true
          resources:
            {{- toYaml .Values.cloudSqlProxy.resources | nindent 12 }}
        {{- end }}

        - name: keycloak
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.containerSecurityContext.runAsUser }}
          args:
            - start
            {{- if ne .Values.realm.import "none" }}
            - --import-realm
            {{- end }}
            - --health-enabled=true
            - --metrics-enabled=true
            - --http-management-scheme=http
            - --log-level={{ .Values.keycloak.logLevel }}

          ports:
            - name: http
              containerPort: {{ .Values.keycloak.httpPort }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.keycloak.httpsPort }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.keycloak.managementPort }}
              protocol: TCP

          env:
            - name: KC_HTTP_PORT
              value: {{ .Values.keycloak.httpPort | quote }}
            - name: KC_HTTPS_PORT
              value: {{ .Values.keycloak.httpsPort | quote }}
            - name: KC_HOSTNAME
              value: {{ .Values.keycloak.hostname | quote }}
            - name: KC_HOSTNAME_DEBUG
              value: {{ .Values.keycloak.hostnameDebug | quote }}
            - name: KC_HOSTNAME_STRICT
              value: {{ .Values.keycloak.hostnameStrict | quote }}
            {{- if .Values.keycloak.proxyHeaders }}
            - name: KC_PROXY_HEADERS
              value: {{ .Values.keycloak.proxyHeaders | quote }}
            {{- else if .Values.keycloak.proxy }}
            - name: KC_PROXY
              value: {{ .Values.keycloak.proxy | quote }}
            {{- end }}
            - name: KC_HTTP_ENABLED
              value: {{ .Values.keycloak.httpEnabled | quote }}
            - name: KC_HTTP_RELATIVE_PATH
              value: {{ .Values.keycloak.httpRelativePath | quote }}
            - name: KC_TRANSACTION_XA_ENABLED
              value: {{ .Values.keycloak.transactionXaEnabled | quote }}
            - name: KC_LOG_LEVEL
              value: {{ .Values.keycloak.logLevel | quote }}
            - name: KC_LOG
              value: {{ .Values.keycloak.log | quote }}

            - name: KC_DB
              value: {{ .Values.keycloak.db.type | quote }}
            {{- if .Values.keycloak.db.schema }}
            - name: KC_DB_SCHEMA
              value: {{ .Values.keycloak.db.schema | quote }}
            {{- end }}
            {{- if .Values.keycloak.db.driver }}
            - name: KC_DB_DRIVER
              value: {{ .Values.keycloak.db.driver | quote }}
            {{- end }}
            - name: KC_DB_POOL_INITIAL_SIZE
              value: {{ .Values.keycloak.db.poolInitialSize | quote }}
            - name: KC_DB_POOL_MIN_SIZE
              value: {{ .Values.keycloak.db.poolMinSize | quote }}
            - name: KC_DB_POOL_MAX_SIZE
              value: {{ .Values.keycloak.db.poolMaxSize | quote }}
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.credentialsSecret }}
                  key: KC_DB_USERNAME
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.credentialsSecret }}
                  key: KC_DB_PASSWORD
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.credentialsSecret }}
                  key: KC_DB_URL
            {{- if .Values.keycloak.db.urlPropertiesSecret }}
            - name: KC_DB_URL_PROPERTIES
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.db.credentialsSecret }}
                  key: KC_DB_URL_PROPERTIES
            {{- end }}

            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /secrets/tls/server-certificate.pem
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /secrets/tls/server-certificate-key.pem

            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.adminCredentialsSecret }}
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.adminCredentialsSecret }}
                  key: KEYCLOAK_ADMIN_PASSWORD

            {{- if .Values.realm.file }}
            - name: KC_FEATURES
              value: {{ .Values.realm.features | quote }}
            - name: JAVA_OPTS_APPEND
              value: >-
                -Dkeycloak.migration.action=import
                -Dkeycloak.migration.provider=dir
                -Dkeycloak.migration.dir=/opt/keycloak/data/import
                -Dkeycloak.migration.strategy={{ if eq .Values.realm.import "overwrite" }}OVERWRITE_EXISTING{{ else }}IGNORE_EXISTING{{ end }}
                -Dkeycloak.migration.replace-placeholders=true

            - name: KC_REALM
              value: {{ .Values.realm.realm | quote }}
            - name: KC_REALM_DISPLAY_NAME
              value: {{ .Values.realm.displayName | quote }}

            - name: KC_ACCESS_TOKEN_LIFESPAN
              value: {{ .Values.realm.accessTokenLifespan | quote }}
            - name: KC_SSO_SESSION_IDLE_TIMEOUT
              value: {{ .Values.realm.ssoSessionIdleTimeout | quote }}
            - name: KC_SSO_SESSION_MAX_LIFESPAN
              value: {{ .Values.realm.ssoSessionMaxLifespan | quote }}
            - name: KC_OFFLINE_SESSION_IDLE_TIMEOUT
              value: {{ .Values.realm.offlineSessionIdleTimeout | quote }}
            - name: KC_ACCESS_CODE_LIFESPAN
              value: {{ .Values.realm.accessCodeLifespan | quote }}

            - name: DATAFABRIC_PUBLIC_CLIENT_ID
              value: {{ .Values.realm.publicClient.clientId | quote }}
            - name: DATAFABRIC_PUBLIC_CLIENT_NAME
              value: {{ .Values.realm.publicClient.name | quote }}
            - name: DATAFABRIC_PUBLIC_REDIRECT_URI_1
              value: {{ .Values.realm.publicClient.redirectUri1 | quote }}
            - name: DATAFABRIC_PUBLIC_REDIRECT_URI_2
              value: {{ .Values.realm.publicClient.redirectUri2 | quote }}
            - name: DATAFABRIC_PUBLIC_WEB_ORIGIN_1
              value: {{ .Values.realm.publicClient.webOrigin1 | quote }}
            - name: DATAFABRIC_PUBLIC_WEB_ORIGIN_2
              value: {{ .Values.realm.publicClient.webOrigin2 | quote }}
            - name: DATAFABRIC_PUBLIC_POST_LOGOUT_REDIRECT_URIS
              value: {{ .Values.realm.publicClient.postLogoutRedirectUris | quote }}

            - name: DATAFABRIC_ADMIN_PUBLIC_CLIENT_ID
              value: {{ .Values.realm.adminPublicClient.clientId | quote }}
            - name: DATAFABRIC_ADMIN_PUBLIC_CLIENT_NAME
              value: {{ .Values.realm.adminPublicClient.name | quote }}
            - name: DATAFABRIC_ADMIN_PUBLIC_REDIRECT_URI_1
              value: {{ .Values.realm.adminPublicClient.redirectUri1 | quote }}
            - name: DATAFABRIC_ADMIN_PUBLIC_REDIRECT_URI_2
              value: {{ .Values.realm.adminPublicClient.redirectUri2 | quote }}
            - name: DATAFABRIC_ADMIN_PUBLIC_WEB_ORIGIN_1
              value: {{ .Values.realm.adminPublicClient.webOrigin1 | quote }}
            - name: DATAFABRIC_ADMIN_PUBLIC_WEB_ORIGIN_2
              value: {{ .Values.realm.adminPublicClient.webOrigin2 | quote }}
            - name: DATAFABRIC_ADMIN_PUBLIC_POST_LOGOUT_REDIRECT_URIS
              value: {{ .Values.realm.adminPublicClient.postLogoutRedirectUris | quote }}

            - name: DATAFABRIC_ADMIN_CONFIDENTIAL_CLIENT_ID
              value: {{ .Values.realm.adminConfidentialClient.clientId | quote }}
            - name: DATAFABRIC_ADMIN_CONFIDENTIAL_CLIENT_NAME
              value: {{ .Values.realm.adminConfidentialClient.name | quote }}
            - name: DATAFABRIC_ADMIN_CONFIDENTIAL_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.realm.clientSecretsSecret }}
                  key: DATAFABRIC_ADMIN_CONFIDENTIAL_CLIENT_SECRET
            {{- end }}

            {{- if .Values.cloudSqlProxy.enabled }}
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/gcp/gcp-service-account-credentials.json
            {{- end }}

            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          volumeMounts:
            - name: keycloak-tls-server-cert-volume
              mountPath: /secrets/tls
              readOnly: true
            {{- if .Values.realm.file }}
            - name: keycloak-realm-import-volume
              mountPath: /opt/keycloak/data/import
              readOnly: true
            {{- end }}
            {{- if .Values.cloudSqlProxy.enabled }}
            - name: gcp-service-account-credentials-volume
              mountPath: /secrets/gcp
              readOnly: true
            {{- end }}
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port | default .Values.keycloak.managementPort }}
              scheme: {{ .Values.livenessProbe.scheme | default "HTTP" }}
              {{- with .Values.livenessProbe.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds | default 3 }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}

          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port | default .Values.keycloak.managementPort }}
              scheme: {{ .Values.readinessProbe.scheme | default "HTTP" }}
              {{- with .Values.readinessProbe.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds | default 3 }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}

          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: {{ .Values.startupProbe.port | default .Values.keycloak.managementPort }}
              scheme: {{ .Values.startupProbe.scheme | default (.Values.readinessProbe.scheme | default "HTTP") }}
              {{- with .Values.startupProbe.httpHeaders }}
              httpHeaders:
                {{- toYaml . | nindent 16 }}
              {{- end }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds | default 3 }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}