apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: itineris-cql-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "itineris.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ include "itineris.fullname" . }}-k8ssandra-store
    kind: SecretStore
  target:
    name: itineris-cql-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.cql.credentialsSecret.name }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.cql.credentialsSecret.name }}
        property: password