---
apiVersion: v1
kind: Service
metadata:
  name: hugegraph-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hugegraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  clusterIP: None
  selector:
    {{- include "hugegraph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.server.ports.http }}
      targetPort: http
    - name: gremlin
      port: {{ .Values.server.ports.gremlin }}
      targetPort: gremlin
    - name: rpc
      port: {{ .Values.server.ports.rpc }}
      targetPort: rpc
---
apiVersion: v1
kind: Service
metadata:
  name: hugegraph-server-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hugegraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    {{- include "hugegraph.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.server.ports.http }}
      targetPort: http
    - name: gremlin
      port: {{ .Values.server.ports.gremlin }}
      targetPort: gremlin
    - name: rpc
      port: {{ .Values.server.ports.rpc }}
      targetPort: rpc