apiVersion: v1
kind: ConfigMap
metadata:
  name: hugegraph-server-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hugegraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
data:
  log4j2.xml: |
{{ .Files.Get "files/server/log4j2.xml" | indent 4 }}
  config-gen.sh: |
{{ .Files.Get "files/server/config-gen.sh" | indent 4 }}
  gremlin-server.yaml.tpl: |
{{ .Files.Get "files/server/gremlin-server.yaml.tpl" | indent 4 }}
  rest-server.properties.tpl: |
{{ .Files.Get "files/server/rest-server.properties.tpl" | indent 4 }}
  hugegraph.properties.tpl: |
{{ .Files.Get "files/server/hugegraph.properties.tpl" | indent 4 }}