apiVersion: v1
kind: ConfigMap
metadata:
  name: hugegraph-store-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hugegraph.labels" . | nindent 4 }}
    app.kubernetes.io/component: store
data:
  log4j2.xml: |
{{ .Files.Get "files/store/log4j2.xml" | indent 4 }}
  application.yaml.tpl: |
{{ .Files.Get "files/store/application.yaml.tpl" | indent 4 }}
  config-gen.sh: |
{{ .Files.Get "files/store/config-gen.sh" | indent 4 }}