---
# prettier-ignore
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docling-serve.fullname" . }}
  labels:
    {{- include "docling-serve.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
  selector:
    {{- include "docling-serve.selectorLabels" . | nindent 4 }}
