---
apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ .Values.clusterName }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.kafkaVersion }}
    listeners:
      - name: plain
        port: {{ .Values.listeners.clientPlainPort }}
        type: internal
        tls: false
      - name: tls
        port: {{ .Values.listeners.clientTlsPort }}
        type: internal
        tls: true
      - name: internal
        port: {{ .Values.listeners.interBrokerPort }}
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: {{ .Values.config.offsetsTopicReplicationFactor }}
      transaction.state.log.replication.factor: {{ .Values.config.transactionStateLogReplicationFactor }}
      transaction.state.log.min.isr: {{ .Values.config.transactionStateLogMinIsr }}
      default.replication.factor: {{ .Values.config.defaultReplicationFactor }}
      min.insync.replicas: {{ .Values.config.minInsyncReplicas }}
      log.retention.hours: {{ .Values.config.logRetentionHours }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
