---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: {{ .Values.serving.namespace }}
spec:
  version: {{ .Values.knativeVersion }}
  ingress:
    istio:
      enabled: true
      {{- if .Values.serving.gatewayName }}
      {{ .Values.serving.localGatewayName }}:
        selector:
          gateway.networking.k8s.io/gateway-name: {{ .Values.serving.gatewayName }}
      {{- end }}
  config:
    network:
      ingress-class: "istio.ingress.networking.knative.dev"
    {{- if .Values.serving.config.domain }}
    domain:
      {{ .Values.serving.config.domain }}: ""
    {{- end }}
    deployment:
      progress-deadline: {{ .Values.serving.config.progressDeadline | default "1800s" }}
    features:
      kubernetes.podspec-init-containers: "enabled"
      kubernetes.podspec-persistent-volume-claim: "enabled"
      kubernetes.podspec-persistent-volume-write: "enabled"
    istio:
      local-gateways: |
        - name: {{ .Values.serving.localGatewayName }}
          namespace: {{ .Values.serving.namespace }}
          service: {{ .Values.serving.platformLocalGatewayName }}.{{ .Values.serving.istioNamespace }}.svc.cluster.local
  additionalManifests:
    - URL: https://github.com/knative/net-istio/releases/download/knative-v{{ .Values.knativeVersion }}/net-istio.yaml