name: data-fabric
auth: true

cassandra:
  clusterName: data-fabric
  serverVersion: "5.0.6"

  serverImage:
    enabled: true
    registry: docker.io
    repository: k8ssandra/cass-management-api
    tag: "5.0.6-ubi"
    name: ""
    pullPolicy: IfNotPresent
    pullSecretRef: ""

  defaults:
    storageClassName: standard
    storageSize: 48Gi
    softPodAntiAffinity: false

    resources:
      requests:
        cpu: "1"
        memory: 4Gi
      limits:
        cpu: "2"
        memory: 4Gi

    jvm:
      gc: G1GC
      heapInitialSize: 2Gi
      heapMaxSize: 2Gi

  rackTemplate:
    namePrefix: rack
    startAt: 1

  datacenters:
    - name: dc1
      size: 3
      rackCount: 3

      storageClassName: standard
      storageSize: 48Gi
      softPodAntiAffinity: false

      resources:
        requests:
          cpu: "1"
          memory: 4Gi
        limits:
          cpu: "2"
          memory: 4Gi

      jvm:
        gc: G1GC
        heapInitialSize: 2Gi
        heapMaxSize: 2Gi

reaper:
  enabled: true

  containerImage:
    enabled: true
    registry: docker.io
    repository: thelastpickle/reaper
    tag: "4.2.0"
    name: ""
    pullPolicy: IfNotPresent
    pullSecretRef: ""

  deploymentMode: PER_DC
  heapSize: 2Gi

  httpManagement:
    enabled: true

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi

  autoScheduling:
    enabled: true
