apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "livy.fullname" . }}
  labels:
    {{- include "livy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "livy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "livy.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "livy.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: livy
          image: {{ include "livy.serverImage" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: LIVY_HOME
              value: {{ .Values.paths.livyHome | quote }}
            - name: LIVY_CONF_DIR
              value: {{ .Values.paths.livyConfDir | quote }}
            - name: SPARK_HOME
              value: {{ .Values.paths.sparkHome | quote }}
            - name: SPARK_CONF_DIR
              value: {{ .Values.paths.sparkConfDir | quote }}
            - name: PYSPARK_PYTHON
              value: python3
            {{- $s3CredentialsSecretName := include "livy.s3CredentialsSecretName" . }}
            {{- with $s3CredentialsSecretName }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ . | quote }}
                  key: {{ $.Values.spark.s3.credentials.accessKeyIdKey | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ . | quote }}
                  key: {{ $.Values.spark.s3.credentials.secretAccessKeyKey | quote }}
            {{- if $.Values.spark.s3.credentials.sessionToken.enabled }}
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ . | quote }}
                  key: {{ $.Values.spark.s3.credentials.sessionToken.key | quote }}
            {{- end }}
            {{- if $.Values.spark.s3.credentials.region.enabled }}
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ . | quote }}
                  key: {{ $.Values.spark.s3.credentials.region.key | quote }}
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ . | quote }}
                  key: {{ $.Values.spark.s3.credentials.region.key | quote }}
            {{- end }}
            {{- end }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.livy.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: {{ printf "%s/livy.conf" .Values.paths.livyConfDir | quote }}
              subPath: livy.conf
            - name: config
              mountPath: {{ printf "%s/spark-defaults.conf" .Values.paths.sparkConfDir | quote }}
              subPath: spark-defaults.conf
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.probes.liveness.enabled }}
          livenessProbe:
            httpGet:
              path: /sessions
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- end }}
          {{- if .Values.probes.readiness.enabled }}
          readinessProbe:
            httpGet:
              path: /sessions
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "livy.fullname" . }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
