{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "ClusterRole" "Role" .Values.rbac.clusterWide }}
metadata:
  name: {{ include "livy.fullname" . }}
  labels:
    {{- include "livy.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - configmaps
      - persistentvolumeclaims
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  {{- with .Values.rbac.extraRules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "ClusterRoleBinding" "RoleBinding" .Values.rbac.clusterWide }}
metadata:
  name: {{ include "livy.fullname" . }}
  labels:
    {{- include "livy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ ternary "ClusterRole" "Role" .Values.rbac.clusterWide }}
  name: {{ include "livy.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "livy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
  {{- if ne (include "livy.sparkServiceAccountName" .) (include "livy.serviceAccountName" .) }}
  - kind: ServiceAccount
    name: {{ include "livy.sparkServiceAccountName" . }}
    namespace: {{ include "livy.sparkNamespace" . }}
  {{- end }}
{{- end }}
