{{- if .Values.spark.s3.credentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livy.s3CredentialsSecretName" . }}
  labels:
    {{- include "livy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.spark.s3.credentials.accessKeyIdKey }}: {{ required "spark.s3.credentials.accessKeyId is required when spark.s3.credentials.create=true" .Values.spark.s3.credentials.accessKeyId | quote }}
  {{ .Values.spark.s3.credentials.secretAccessKeyKey }}: {{ required "spark.s3.credentials.secretAccessKey is required when spark.s3.credentials.create=true" .Values.spark.s3.credentials.secretAccessKey | quote }}
  {{- if .Values.spark.s3.credentials.sessionToken.enabled }}
  {{ .Values.spark.s3.credentials.sessionToken.key }}: {{ required "spark.s3.credentials.sessionToken.value is required when spark.s3.credentials.sessionToken.enabled=true and spark.s3.credentials.create=true" .Values.spark.s3.credentials.sessionToken.value | quote }}
  {{- end }}
  {{- if .Values.spark.s3.credentials.region.enabled }}
  {{ .Values.spark.s3.credentials.region.key }}: {{ required "spark.s3.credentials.region.value is required when spark.s3.credentials.region.enabled=true and spark.s3.credentials.create=true" .Values.spark.s3.credentials.region.value | quote }}
  {{- end }}
{{- end }}
