{{- if .Values.virtualService.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "livy.fullname" . }}
  {{- with .Values.virtualService.namespace }}
  namespace: {{ . | quote }}
  {{- end }}
  labels:
    {{- include "livy.labels" . | nindent 4 }}
  {{- with .Values.virtualService.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hosts:
    {{- toYaml .Values.virtualService.hosts | nindent 4 }}
  gateways:
    {{- toYaml .Values.virtualService.gateways | nindent 4 }}
  http:
    {{- if .Values.virtualService.http }}
    {{- toYaml .Values.virtualService.http | nindent 4 }}
    {{- else }}
    {{- $pathPrefix := trimSuffix "/" .Values.virtualService.pathPrefix }}
    - name: {{ include "livy.fullname" . }}
      {{- if $pathPrefix }}
      match:
        - uri:
            exact: {{ $pathPrefix | quote }}
        - uri:
            prefix: {{ printf "%s/" $pathPrefix | quote }}
      {{- end }}
      {{- with .Values.virtualService.rewriteUri }}
      rewrite:
        uri: {{ . | quote }}
      {{- end }}
      route:
        - destination:
            host: {{ printf "%s.%s.svc.cluster.local" (include "livy.fullname" .) .Release.Namespace }}
            port:
              number: {{ .Values.service.port }}
    {{- end }}
{{- end }}
