apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opensearch.name" . }}
    app.kubernetes.io/component: search
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "opensearch.name" . }}
    app.kubernetes.io/component: search
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
    - name: transport
      protocol: TCP
      port: {{ .Values.service.ports.transport }}
      targetPort: {{ .Values.service.ports.transport }}
    - name: metrics
      protocol: TCP
      port: {{ .Values.service.ports.metrics }}
      targetPort: {{ .Values.service.ports.metrics }}
