apiVersion: v1
kind: Service
metadata:
  name: {{ include "opensearch.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opensearch.name" . }}
    app.kubernetes.io/component: search
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "opensearch.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.ports.http }}
      targetPort: 9200
      name: http
    - protocol: TCP
      port: {{ .Values.service.ports.metrics }}
      targetPort: 9600
      name: metrics
  type: {{ .Values.service.type }}
