apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "opensearch.fullname" . }}-node-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.certificates.node.secretName }}
  duration: 2160h        # 90 days
  renewBefore: 360h      # 15 days before expiration
  commonName: {{ .Values.opensearch.host }}
  dnsNames:
    - {{ .Values.opensearch.host }}
    - {{ include "opensearch.fullname" . }}
    - {{ include "opensearch.fullname" . }}.{{ .Release.Namespace }}.svc
  issuerRef:
    name: {{ .Values.certificates.issuer.name }}
    kind: {{ .Values.certificates.issuer.kind | default "ClusterIssuer" }}
