apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminSecret.name }}
  labels:
    app.kubernetes.io/name: {{ include "opensearch.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: opensearch
type: Opaque
stringData:
    {{ printf "%s: %s" .Values.adminSecret.key (quote .Values.adminSecret.value) | nindent 2 }}
