apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opensearch.fullname" . }}
  labels:
    app: {{ include "opensearch.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "opensearch.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "opensearch.name" . }}
    spec:
      containers:
        - name: opensearch
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9600
              name: metrics
          env:
            - name: discovery.type
              value: "single-node"
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.adminSecret.name }}
                  key: {{ .Values.adminSecret.key }}
          volumeMounts:
            - name: storage
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "opensearch.fullname" . }}-pvc
