apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminSecret.name }}
  labels:
    app: {{ include "opensearch.name" . }}
type: Opaque
stringData:
  {{ printf "%s: %s" .Values.adminSecret.key (quote .Values.adminSecret.value) | nindent 2 }}

