{{- if and (.Values.dashboards.ssl.verificationMode) (ne (.Values.dashboards.ssl.verificationMode | lower) "none") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dashboards.ssl.caSecretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  ca.crt: {{ .Values.dashboards.ssl.caBundle | quote }}
{{- end }}
