apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "opensearch.name" . }}
    app.kubernetes.io/component: opensearch
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  {{ .Values.adminSecret.key }}: {{ .Values.adminSecret.value | quote }}

