apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificates.node.certificateName | default (printf "%s-node-cert" (include "opensearch.fullname" .)) }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.certificates.node.secretName }}
  duration: 2160h # 90 days
  renewBefore: 360h
  commonName: {{ .Values.opensearch.host }}
  dnsNames:
    - {{ .Values.opensearch.host }}
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: {{ .Values.certificates.issuer.name }}
    kind: {{ .Values.certificates.issuer.kind | default "ClusterIssuer" }}
  usages:
    - digital signature
    - key encipherment
    - server auth
    - client auth

