apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-custom-config
  labels:
    app.kubernetes.io/name: {{ include "opensearch.name" . }}
    app.kubernetes.io/component: config
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
data:
  opensearch.yml: |
    cluster.name: {{ .Values.clusterName }}
    node.name: {{ .Values.nodeName }}
    path.data: /usr/share/opensearch/data
    path.logs: /usr/share/opensearch/logs
    network.host: 0.0.0.0
    http.port: {{ .Values.service.ports.http }}
    transport.port: {{ .Values.service.ports.transport }}
    discovery.type: single-node

    plugins.security.disabled: {{ .Values.security.disable | default "false" }}

    {{- with .Values.extraConfig }}
{{ toYaml . | indent 4 }}
    {{- end }}

