apiVersion: v2
name: docling-serve
description: Helm chart for deploying Docling Serve with PVC-backed cache and configurable backend models.
type: application
version: "0.1.3"
appVersion: "latest"
keywords:
  - docling
  - NLP
  - model-serving
  - PVC
maintainers:
  - name: Prashanth Nandavanam
    email: pn@forwardmeasure.com
