{{- if and .Values.nominatim.enabled .Values.nominatim.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geocoding.nominatimServiceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "geocoding.labels" . | nindent 4 }}
    app.kubernetes.io/component: nominatim
  {{- with .Values.nominatim.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.nominatim.service.type }}
  ports:
    - name: http
      port: {{ .Values.nominatim.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "geocoding.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nominatim
{{- end }}
