{{- if .Values.gcp.workloadIdentity.enabled }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: {{ include "keycloak.fullname" . }}-gcp-sa-policy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: {{ include "keycloak.fullname" . }}-gcp-sa
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:{{ printf "%s.svc.id.goog[%s/%s]" .Values.gcp.workloadIdentity.gcpProjectId .Release.Namespace (include "keycloak.serviceAccountName" .) }}
    - role: roles/cloudsql.client
      members:
        - serviceAccount:{{ printf "%s.svc.id.goog[%s/%s]" .Values.gcp.workloadIdentity.gcpProjectId .Release.Namespace (include "keycloak.serviceAccountName" .) }}
{{- end }}