apiVersion: v1
kind: Service
metadata:
  name: {{ include "triton-serving.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "triton-serving.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $idx, $model := .Values.models }}
    {{- $httpPort := add 8000 (mul $idx 10) }}
    {{- $grpcPort := add 8001 (mul $idx 10) }}
    {{- $metricsPort := add 8002 (mul $idx 10) }}
    - name: {{ printf "http-m%d" $idx }}
      port: {{ $httpPort }}
      targetPort: {{ printf "http-m%d" $idx }}
      protocol: TCP
    - name: {{ printf "grpc-m%d" $idx }}
      port: {{ $grpcPort }}
      targetPort: {{ printf "grpc-m%d" $idx }}
      protocol: TCP
    - name: {{ printf "metrics-m%d" $idx }}
      port: {{ $metricsPort }}
      targetPort: {{ printf "metrics-m%d" $idx }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "triton-serving.selectorLabels" . | nindent 4 }}