apiVersion: v2
name: keycloak
description: Helm chart for deploying Keycloak with StatefulSet, TLS, and external database support.
type: application
version: "0.0.8"
appVersion: "26.5"
keywords:
  - keycloak
  - iam
  - authentication
  - authorization
maintainers:
  - name: Prashanth Nandavanam
    email: pn@forwardmeasure.com
