# prettier-ignore

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zookeeper.fullname" . }}-config
data:
  zoo.cfg: |-
    tickTime={{ .Values.zookeeperConfig.tickTime }}
    initLimit={{ .Values.zookeeperConfig.initLimit }}
    syncLimit={{ .Values.zookeeperConfig.syncLimit }}
    autopurge.purgeInterval={{ .Values.zookeeperConfig.autopurgePurgeInterval }}
    autopurge.snapRetainCount={{ .Values.zookeeperConfig.autopurgeSnapRetainCount }}
    maxClientCnxns={{ .Values.zookeeperConfig.maxClientCnxns }}
    dataDir=/data
    dataLogDir=/datalog
    standaloneEnabled=false
    admin.enableServer=true
    clientPort={{ .Values.service.ports.client }}
    {{- $root := . }}
    {{- $ss := include "zookeeper.fullname" $root }}
    {{- $svc := include "zookeeper.headlessName" $root }}
    {{- range $i := until (int $root.Values.replicaCount) }}
    {{- $id := add $i 1 }}
    # Pod: {{ $ss }}-{{ $i }}
    server.{{ $id }}={{ $ss }}-{{ $i }}.{{ $svc }}:{{ $root.Values.service.ports.quorum }}:{{ $root.Values.service.ports.election }};{{ $root.Values.service.ports.client }}
    {{- end }}
