apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.headlessName" . }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.ports.client }}
      name: client
    - port: {{ .Values.service.ports.quorum }}
      name: quorum
    - port: {{ .Values.service.ports.election }}
      name: election
  selector:
    app: {{ include "zookeeper.name" . }}
