# prettier-ignore

apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}
  labels:
    {{- include "zookeeper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: client
      port: {{ .Values.service.ports.client }}
      targetPort: client
    - name: quorum
      port: {{ .Values.service.ports.quorum }}
      targetPort: quorum
    - name: election
      port: {{ .Values.service.ports.election }}
      targetPort: election
  selector:
    {{- include "zookeeper.selectorLabels" . | nindent 4 }}
