apiVersion: v1
entries:
  opensearch:
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2025-07-04T21:45:53.040986368-04:00"
    description: A Helm chart for OpenSearch Cluster deployment
    digest: 0595696a40eb7e03d286e4c231ba5df4b46a2f5157de2a865d5da35d595a5c6a
    name: opensearch
    urls:
    - https://forwardmeasure.github.io/helm-charts/charts/opensearch-1.0.6.tgz
    version: 1.0.6
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2025-07-04T21:45:53.040762916-04:00"
    description: A Helm chart for OpenSearch Cluster deployment
    digest: 1fa8290ec0745f4ebf53bb977d2dbf34cabe836fc8e8e4d32d754d7c54aa2b52
    name: opensearch
    urls:
    - https://forwardmeasure.github.io/helm-charts/charts/opensearch-1.0.5.tgz
    version: 1.0.5
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2025-07-04T21:45:53.040549732-04:00"
    description: A Helm chart for OpenSearch Cluster deployment
    digest: 843495e8e0828e1881b317828d7a69f7350d84463ffdcf5cd941a633edbbaff2
    name: opensearch
    urls:
    - https://forwardmeasure.github.io/helm-charts/charts/opensearch-1.0.4.tgz
    version: 1.0.4
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2025-07-04T21:45:53.040318627-04:00"
    description: A Helm chart for OpenSearch Cluster deployment
    digest: 0de7bef06da4dfb915af35df199b61bd78d6f7a93fdaaa26d649b30e30d14041
    name: opensearch
    urls:
    - https://forwardmeasure.github.io/helm-charts/charts/opensearch-1.0.3.tgz
    version: 1.0.3
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2025-07-04T21:45:53.040113185-04:00"
    description: A Helm chart for OpenSearch Cluster deployment
    digest: 8431fd1d50378a12dafefcf7d3e09fbcb6f9931a07f26d84e366249a804e3f56
    name: opensearch
    urls:
    - https://forwardmeasure.github.io/helm-charts/charts/opensearch-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2025-07-04T21:45:53.039869535-04:00"
    description: A Helm chart for OpenSearch Cluster deployment
    digest: 112ac7db3499c964ac52410f9b86c8cdb4de3e0ddf674165abfe761f34921ec9
    name: opensearch
    urls:
    - https://forwardmeasure.github.io/helm-charts/charts/opensearch-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2025-07-04T21:45:53.039625282-04:00"
    description: A Helm chart for OpenSearch Cluster deployment
    digest: d9adad0b52fa4ec07373973fbde3cc820042d0fc4b95eef9b155ebf57e3c34ef
    name: opensearch
    urls:
    - https://forwardmeasure.github.io/helm-charts/charts/opensearch-1.0.0.tgz
    version: 1.0.0
  spark-cluster:
  - apiVersion: v2
    appVersion: 4.0.0
    created: "2025-03-25T15:01:48.430567672-04:00"
    description: A Helm chart for Spark Cluster deployment
    digest: 152ca802f469a5437325682afa35734a72b2dbd867cd3b550502c66cb392bf84
    name: spark-cluster
    urls:
    - https://forwardmeasure.github.io/spark-cluster-helm-chart/spark-cluster-1.0.0.tgz
    version: 1.0.0
generated: "2025-07-04T21:45:53.039284019-04:00"
