apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: opensearch
    releaseName: opensearch
    namespace: opensearch-cluster
    repo: file://./helm-chart-sources
    valuesFile: values.yaml

